<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Overlay/EorzeaStartSchedule.cs" Link="EorzeaStartSchedule.cs" />
    <Compile Include="../../Localization/UiText.cs" Link="UiText.cs" />
    <Compile Include="../../Windows/PreviewAnimation.cs" Link="PreviewAnimation.cs" />
  </ItemGroup>
</Project>
